// <auto-generated />
using System;
using ConciliacaoBancariaAuvo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConciliacaoBancariaAuvo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210603215731_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConciliacaoBancariaAuvo.Entities.Extrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DataLancamento");

                    b.Property<string>("Descricao");

                    b.Property<string>("Observacao");

                    b.Property<string>("Ofx");

                    b.Property<string>("Tipo");

                    b.Property<string>("Valor");

                    b.HasKey("Id");

                    b.ToTable("Extratos");
                });
#pragma warning restore 612, 618
        }
    }
}
